spring:
  cloud:
    gateway:
      routes:
        - id: mall-gateway-baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: mall-gateway-qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq