spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-third-party
    alicloud:
      access-key: #
      secret-key: #
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        appCode: 16dd6c32315c411ab10d8061b42dfe52
server:
  port: 31000
