spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-third-party
    alicloud:
      access-key: LTAI4GCdBUWRVWTyQjxwT5hU
      secret-key: oqCP5jnqIKvz45kSaCsn8hlvEwVSZY
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
server:
  port: 30000
